### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by C-Ezra-M** [C-Ezra-M/coben-calc#1]
- [x] Separate test data from the HTML
- [x] Beautify the page, make it look consistent
- [x] Add "Fork me on GitHub"
- [x] Add JSON output (to allow more precise floats due to issues with MavoScript's `digits` function)
